### ISSUE TITLE
non-standard regex problem

### ISSUE THREAD

**Issue by enexusde** [BorisMoore/jsrender#302]
Use canoo webtest 
```
<dependency>
	<groupId>com.canoo.webtest</groupId>
	<artifactId>webtest</artifactId>
	<version>3.0</version>
	<scope>test</scope>
</dependency>
```

Results in 
```
Exception in thread "HtmlUnit Managed Thread #83 for WebWindow : XMLHttpRequest.send" java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at com.gargoylesoftware.htmlunit.javascript.regexp.HtmlUnitRegExpProxy.action(HtmlUnitRegExpProxy.java:75)
	at org.mozilla.javascript.NativeString.execIdCall(NativeString.java:380)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3330)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2487)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:192)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:472)
	at com.gargoylesoftware.htmlunit.javascript.host.XMLHttpRequest.setState(XMLHttpRequest.java:142)
	at com.gargoylesoftware.htmlunit.javascript.host.XMLHttpRequest.doSend(XMLHttpRequest.java:413)
	at com.gargoylesoftware.htmlunit.javascript.host.XMLHttpRequest.access$000(XMLHttpRequest.java:54)
	at com.gargoylesoftware.htmlunit.javascript.host.XMLHttpRequest$1.run(XMLHttpRequest.java:361)
	at org.mozilla.javascript.Context.call(Context.java:515)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:507)
	at com.gargoylesoftware.htmlunit.javascript.host.XMLHttpRequest$2.run(XMLHttpRequest.java:367)
	at java.lang.Thread.run(Thread.java:745)
	at com.gargoylesoftware.htmlunit.ThreadManager$1.run(ThreadManager.java:116)
```

**Comment by enexusde** [comment]
By the way, the target of the query is random but the value is "\\$&" i guess it is this line:

			// Compile to AST and then to compiled function
			tmplFn(tmplOrMarkup.replace(rEscapeQuotes, "\\$&"), tmpl);

**Comment by BorisMoore** [comment]
It is non standard to use RegEx.lastMatch() - as a programmatic way of accessing the last match. But it is standard to use `"$&"` as a replacement pattern in a replacement string, in the `someString.replace(regex, replacementstring)` call - which is what JsRender is doing.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace, where it says:

> The replacement string can include the following special replacement patterns:
> 
> Pattern	Inserts
> ...
> $&	Inserts the matched substring.

The regex in that line of code is rEscapeQuotes, which is declared as 	`rEscapeQuotes = /['"\\]/g` - and is a valid JavaScript regex.

That line is looking for `'` `"` or` \` and replacing them with the same character preceded by `\`.

**Comment by enexusde** [comment]
For your information, i created a bug-report at https://bugs.openjdk.java.net/browse/JDK-8162831 for supporting $& in regex.
